### ISSUE TITLE
Add Why Java and Quarkus are important for your business to Publications

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkusio.github.io#662] opened 2020-07-21 20:51 UTC
```
- id: WhyJavaandQuarkusareimportantforyourbusiness-2020-07-19
  type: article 
  title: "Why Java and Quarkus are important for your business"
  date: "2020-07-13"
  author: "Syed Rasheed"
  affiliation: "Red Hat"
  note: "Syed quantifies the benefits of Quarkus"
  url: "https://www.redhat.com/en/blog/why-java-and-quarkus-are-important-your-business?sc_cid=70160000001273HAAQ"
  urldate: "2020-07-21"

```

**Comment by maxandersen** [comment] 2020-09-23 06:34
duplicate of #660

**Closed by maxandersen** 2020-09-23 06:34 UTC
Labels: publication
