### ISSUE TITLE
New S2I Guide does not show up on mobile (on currently live site)

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkusio.github.io#167] opened 2019-04-10 18:48 UTC
When I look at https://quarkus.io/guides/ right now (on mobile), it does not not include the new S2I page, anymore - I could swear that it was there about two days ago? Either there is some hiccup in the release process, or there is a difference on mobile (unlikely).

@cescoffier @gsmet

**Comment by vorburger** [comment] 2019-04-11 17:25
The problem is specific to mobile - see this ![Screenshot_20190411-192131](https://user-images.githubusercontent.com/298598/55977546-5d7c0b80-5c8f-11e9-9e1f-2b4fe2d8d724.jpg) ... the screenshot is incomplete, but if I scroll down on that view the S2I section does not appear.

I'm guessing it needs to be added somewhere else - trying to see where...

**Comment by vorburger** [comment] 2019-04-11 17:26
... it also does not show in the "main text" on the right on desktop (not mobile) - only on the menu on the left. So I gather when we add new guides we have to add them in two places...

**Comment by cescoffier** [comment] 2019-04-12 08:05
We are aware of this. @gsmet was going to update the guide.md.

The issue is that ALL guides must be duplicated on the page, making it very hard to maintain on the long run and making the release process quite error-prone. We want to remove this page or at least generate it from a single source.

**Comment by gsmet** [comment] 2019-04-12 10:01
Yeah, I created the PR a few days ago and @cescoffier just merged it. It's now fixed.

**Closed by gsmet** 2019-04-12 10:01 UTC
