### ISSUE TITLE
Update color scheme to align with logo's

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkusio.github.io#197] opened 2019-05-14 07:11 UTC

**Comment by emmanuelbernard** [comment] 2019-06-04 07:33
Hey @jkbrock any update on this and the other issues assigned to you? You seem to have deserted Quarkus ;)

**Comment by jkbrock** [comment] 2019-06-04 14:02
@emmanuelbernard, not deserted, juggling :)

I'm combining all requests into a single mockup. Adela and I are meeting next week in Raleigh and will be go over them together before submitting. Don't worry, I haven't abandoned you!

**Comment by gsmet** [comment] 2019-07-03 12:15
@jkbrock any news about this? It would be nice to have the colors in line with the logo.

Thanks!

**Comment by jkbrock** [comment] 2019-07-24 19:35
Please look here for the color theme:

https://xd.adobe.com/view/873a5241-8d88-4c7c-7eb7-5d05360e89f9-f10b

**Comment by emmanuelbernard** [comment] 2019-07-25 12:56
Hey Jason, I started to go all in on the comments but I wonder if you want it to be limited to the color in the adobe wireframe?

**Comment by jkbrock** [comment] 2019-07-25 16:36
@emmanuelbernard Nope. The current scope is color, but if there are bigger things to change let's get at 'em. Feel free to light up the comments.

**Comment by jkbrock** [comment] 2019-07-30 17:04
@emmanuelbernard , here's a new mockup with some adjustments to the homepage gradients and a handful of other improvements based on feedback.

https://xd.adobe.com/view/970b175f-98c3-4ec3-78e5-afca3a301d28-e13a/

**Comment by FroMage** [comment] 2019-08-01 13:32
Are we getting rid of the backgrounds then?

**Comment by emmanuelbernard** [comment] 2019-08-01 19:05
> Are we getting rid of the backgrounds then?

In the mockup only the home page has the background yes (AFAIR). Do you think it's a good or a bad thing @FroMage ?

**Comment by FroMage** [comment] 2019-08-02 08:33
I think it was better with the backgrounds, because:

- our style is super minimalist (and retro), so the lack of background feels like it pushed us from minimalist straight into we-haven't-done-any-style territory. it feels bare
- the background currently is not black, and the new style has it pitch black, which feels to me again like a regression into roughness: it feels more stark and aggressive

**Comment by jkbrock** [comment] 2019-08-08 22:12
@FroMage and @emmanuelbernard , how about this as a compromise:

- Moving back to a blue background
- Increasing the visibility of the image on the hero of the homepage
- Repeating the image in the project footer of each page

This way we still have a similar visual style displayed on each page, but it's not interfering with the legibility of the navigation or content at the top of the page.

https://xd.adobe.com/view/5d48cae4-81ab-4b8d-780d-e32c76747c32-2b79/

**Comment by FroMage** [comment] 2019-08-12 09:21
Yeah, I guess it's better.

**Comment by jkbrock** [comment] 2019-08-15 16:44
How about a few extra tweeks:

https://xd.adobe.com/view/5d48cae4-81ab-4b8d-780d-e32c76747c32-2b79/

**Comment by adelasofia** [comment] 2019-11-05 22:46
Closed via https://github.com/quarkusio/quarkusio.github.io/pull/331

**Closed by adelasofia** 2019-11-05 22:46 UTC
