### ISSUE TITLE
Guides page sorty "by category" isn't filtering when search is empty

### ISSUE THREAD

**Issue by insectengine** [quarkusio/quarkusio.github.io#1955] opened 2024-04-18 14:33 UTC
**Describe the bug**
Guides page sorty "by category" isn't filtering the guides. When the user makes a selection in the pulldown, the content should sort by that category. While it used to do so, it no longer does. The "by Version" works, the "by Category" doesn't.

**Which pages**
https://quarkus.io/guides/

**Comment by yrodiere** [comment] 2024-04-18 14:52
@ia3andy I think that's related to your changes no?
Currently away, sorry, can't have a look.

**Comment by ia3andy** [comment] 2024-04-18 15:43
can you check if the request is alright @marko-bekhta ?

**Comment by ia3andy** [comment] 2024-04-18 15:43
```
language: en
contentSnippets: 2
contentSnippetsLength: 120
version: latest
categories: messaging
q: rest
page: 0

**Comment by ia3andy** [comment] 2024-04-18 15:44
Ah just found that switching category isn't updating the result when search is empty, this is a regression

**Comment by ia3andy** [comment] 2024-04-18 15:53
Ok the issue is not that the request and result are wrong, just the regression of changing without searching

**Comment by marko-bekhta** [comment] 2024-04-19 11:05
The fix in the component (https://github.com/quarkusio/search.quarkus.io/pull/242) was deployed. But I think quarkus.io has to be rebuilt to pick it up? (since I see that the search component comes from https://quarkus.io/assets/javascript/search-wc.js)

**Comment by ia3andy** [comment] 2024-04-19 14:37
> The fix in the component ([quarkusio/search.quarkus.io#242](https://github.com/quarkusio/search.quarkus.io/pull/242)) was deployed. But I think quarkus.io has to be rebuilt to pick it up? (since I see that the search component comes from https://quarkus.io/assets/javascript/search-wc.js)

yes

**Comment by marko-bekhta** [comment] 2024-04-30 09:36
We can close this one, the fix has been deployed for a while now.

**Closed** 2024-04-30 12:21 UTC
Labels: area/search
